### ISSUE TITLE
 Linux Install Issue using Cabal

### ISSUE THREAD

**Issue by callalilychen** [meiersi/scyther-proof#13]
I'm trying to install scyther-proof on Arch linux using "cabal install" . I get the following output when attempting that:

Resolving dependencies...
cabal: Could not resolve dependencies:
trying: scyther-proof-0.10.0.0 (user goal)
next goal: time (dependency of scyther-proof-0.10.0.0)
rejecting: time-1.5.0.1/installed-e17..., 1.5.0.1, 1.5 (conflict:
scyther-proof => time>=1.1 && <1.5)
rejecting: time-1.4.2, 1.4.1, 1.4.0.2, 1.4.0.1, 1.4 (conflict: bytestring =>
deepseq==1.4.1.1/installed-c13..., time => deepseq>=1.1 && <1.4)
rejecting: time-1.3, 1.2.0.5, 1.2.0.4, 1.2.0.3, 1.2.0.2, 1.2.0.1, 1.2, 1.1.4
(conflict: base==4.8.0.0/installed-1b6..., time => base>=4 && <4.7)
trying: time-1.1.3
next goal: process (dependency of scyther-proof-0.10.0.0)
rejecting: process-1.2.3.0/installed-3b1... (conflict: process =>
filepath==1.4.0.0/installed-40d..., scyther-proof => filepath>=1.2 && <1.4)
trying: process-1.2.3.0/installed-421...
next goal: unix (dependency of process-1.2.3.0/installed-421...)
rejecting: unix-2.7.1.0/installed-e59... (conflict: time==1.1.3, unix =>
time==1.5.0.1/installed-e17...)
rejecting: unix-2.7.1.0, 2.7.0.1, 2.7.0.0, 2.6.0.1, 2.6.0.0, 2.5.1.1, 2.5.1.0,
2.5.0.0, 2.4.2.0, 2.4.1.0, 2.4.0.2, 2.4.0.1, 2.4.0.0, 2.3.2.0, 2.3.1.0,
2.3.0.0, 2.2.0.0, 2.0 (conflict: process => unix==2.7.1.0/installed-e59...)
Backjump limit reached (change with --max-backjumps).

I do not know, how to force cabal to install an old library. Can you help me to solve this conflicts? Thank you very much.

**Comment by meiersi** [comment]
Hi,

your are trying to install scyther-proof with GHC 7.10.1, which we do not
yet officially support. However, it might just work if you try to install
it with

```
cabal install --allow-newer scyther-proof
```

best regards,
Simon

2015-06-14 12:05 GMT+02:00 callalilychen <notifications@github.com>:

**Comment by meiersi** [comment]
And thanks for reporting this. I hope the allow-newer trick just works. If not, I'll fix the 7.10 issue asap. See this section <https://www.haskell.org/cabal/users-guide/installing-packages.html#miscellaneous-options> for the documentation of the `allow-newer` flag.

**Comment by callalilychen** [comment]
Thank you very much for your help. I have only GHC 7.10.1, because I haven't compiled Haskell program before. With "--allow-newer" flag I also get the following error messages:

Resolving dependencies...
Configuring scyther-proof-0.10.0.0...
Building scyther-proof-0.10.0.0...
Failed to install scyther-proof-0.10.0.0
Build log ( /home/wenwen/.cabal/logs/scyther-proof-0.10.0.0.log ):
Configuring scyther-proof-0.10.0.0...
Building scyther-proof-0.10.0.0...
Preprocessing executable 'scyther-proof' for scyther-proof-0.10.0.0...
[ 1 of 32] Compiling Scyther.Theory.Lexer ( dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs, dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.o )

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:610:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:611:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:612:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:616:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:617:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:621:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:623:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:627:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:629:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:633:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:642:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:656:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:658:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:659:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:660:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:662:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:663:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:664:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:665:5: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:667:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:670:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:671:1: Warning:
    Tab character

dist/build/scyther-proof/scyther-proof-tmp/Scyther/Theory/Lexer.hs:672:1: Warning:
    Tab character
[ 2 of 32] Compiling Data.Color       ( src/Data/Color.hs, dist/build/scyther-proof/scyther-proof-tmp/Data/Color.o )

src/Data/Color.hs:129:1: Warning: Tab character

src/Data/Color.hs:130:1: Warning: Tab character

src/Data/Color.hs:131:1: Warning: Tab character

src/Data/Color.hs:163:1: Warning: Tab character

src/Data/Color.hs:164:1: Warning: Tab character

src/Data/Color.hs:165:1: Warning: Tab character

src/Data/Color.hs:166:1: Warning: Tab character

src/Data/Color.hs:167:1: Warning: Tab character
[ 3 of 32] Compiling Text.Dot         ( src/Text/Dot.hs, dist/build/scyther-proof/scyther-proof-tmp/Text/Dot.o )

src/Text/Dot.hs:14:1: Warning: Tab character

src/Text/Dot.hs:15:1: Warning: Tab character

src/Text/Dot.hs:16:1: Warning: Tab character

src/Text/Dot.hs:16:14: Warning: Tab character

src/Text/Dot.hs:17:1: Warning: Tab character

src/Text/Dot.hs:18:1: Warning: Tab character

src/Text/Dot.hs:19:1: Warning: Tab character

src/Text/Dot.hs:19:17: Warning: Tab character

src/Text/Dot.hs:20:1: Warning: Tab character

src/Text/Dot.hs:21:1: Warning: Tab character

src/Text/Dot.hs:22:1: Warning: Tab character

src/Text/Dot.hs:23:1: Warning: Tab character

src/Text/Dot.hs:24:1: Warning: Tab character

src/Text/Dot.hs:25:1: Warning: Tab character

src/Text/Dot.hs:26:1: Warning: Tab character

src/Text/Dot.hs:27:1: Warning: Tab character

src/Text/Dot.hs:28:1: Warning: Tab character

src/Text/Dot.hs:29:1: Warning: Tab character

src/Text/Dot.hs:30:1: Warning: Tab character

src/Text/Dot.hs:31:1: Warning: Tab character

src/Text/Dot.hs:32:1: Warning: Tab character

src/Text/Dot.hs:33:1: Warning: Tab character

src/Text/Dot.hs:34:1: Warning: Tab character

src/Text/Dot.hs:35:1: Warning: Tab character

src/Text/Dot.hs:36:1: Warning: Tab character

src/Text/Dot.hs:37:1: Warning: Tab character

src/Text/Dot.hs:38:1: Warning: Tab character

src/Text/Dot.hs:39:1: Warning: Tab character

src/Text/Dot.hs:40:1: Warning: Tab character

src/Text/Dot.hs:41:1: Warning: Tab character

src/Text/Dot.hs:42:1: Warning: Tab character

src/Text/Dot.hs:43:1: Warning: Tab character

src/Text/Dot.hs:44:1: Warning: Tab character

src/Text/Dot.hs:45:1: Warning: Tab character

src/Text/Dot.hs:46:1: Warning: Tab character

src/Text/Dot.hs:47:1: Warning: Tab character

src/Text/Dot.hs:48:1: Warning: Tab character

src/Text/Dot.hs:49:1: Warning: Tab character

src/Text/Dot.hs:50:1: Warning: Tab character

src/Text/Dot.hs:51:1: Warning: Tab character

src/Text/Dot.hs:58:1: Warning: Tab character

src/Text/Dot.hs:63:1: Warning: Tab character

src/Text/Dot.hs:64:1: Warning: Tab character

src/Text/Dot.hs:67:1: Warning: Tab character

src/Text/Dot.hs:68:1: Warning: Tab character

src/Text/Dot.hs:69:1: Warning: Tab character

src/Text/Dot.hs:70:1: Warning: Tab character

src/Text/Dot.hs:84:1: Warning: Tab character

src/Text/Dot.hs:85:1: Warning: Tab character

src/Text/Dot.hs:90:1: Warning: Tab character

src/Text/Dot.hs:108:1: Warning: Tab character

src/Text/Dot.hs:114:1: Warning: Tab character

src/Text/Dot.hs:115:1: Warning: Tab character

src/Text/Dot.hs:126:1: Warning: Tab character

src/Text/Dot.hs:127:1: Warning: Tab character

src/Text/Dot.hs:128:1: Warning: Tab character

src/Text/Dot.hs:150:1: Warning: Tab character

src/Text/Dot.hs:163:1: Warning: Tab character

src/Text/Dot.hs:164:1: Warning: Tab character

src/Text/Dot.hs:165:1: Warning: Tab character

src/Text/Dot.hs:171:1: Warning: Tab character

src/Text/Dot.hs:172:1: Warning: Tab character

src/Text/Dot.hs:226:1: Warning: Tab character
[ 4 of 32] Compiling Control.Concurrent.ManagedThreads ( src/Control/Concurrent/ManagedThreads.hs, dist/build/scyther-proof/scyther-proof-tmp/Control/Concurrent/ManagedThreads.o )
[ 5 of 32] Compiling Control.Monad.Label ( src/Control/Monad/Label.hs, dist/build/scyther-proof/scyther-proof-tmp/Control/Monad/Label.o )
[ 6 of 32] Compiling Data.UnionFind   ( src/Data/UnionFind.hs, dist/build/scyther-proof/scyther-proof-tmp/Data/UnionFind.o )
[ 7 of 32] Compiling Text.PrettyPrint.Class ( src/Text/PrettyPrint/Class.hs, dist/build/scyther-proof/scyther-proof-tmp/Text/PrettyPrint/Class.o )
[ 8 of 32] Compiling Control.Monad.BoundedDFS ( src/Control/Monad/BoundedDFS.hs, dist/build/scyther-proof/scyther-proof-tmp/Control/Monad/BoundedDFS.o )
[ 9 of 32] Compiling Paths_scyther_proof ( dist/build/autogen/Paths_scyther_proof.hs, dist/build/scyther-proof/scyther-proof-tmp/Paths_scyther_proof.o )
[10 of 32] Compiling System.Timing    ( src/System/Timing.hs, dist/build/scyther-proof/scyther-proof-tmp/System/Timing.o )
[11 of 32] Compiling System.Isabelle  ( src/System/Isabelle.hs, dist/build/scyther-proof/scyther-proof-tmp/System/Isabelle.o )
[12 of 32] Compiling Control.Basics   ( src/Control/Basics.hs, dist/build/scyther-proof/scyther-proof-tmp/Control/Basics.o )
[13 of 32] Compiling Extension.Prelude ( src/Extension/Prelude.hs, dist/build/scyther-proof/scyther-proof-tmp/Extension/Prelude.o )

src/Extension/Prelude.hs:44:46:
    Ambiguous occurrence ‘sortOn’
    It could refer to either ‘Extension.Prelude.sortOn’,
                             defined at src/Extension/Prelude.hs:56:1
                          or ‘Data.List.sortOn’,
                             imported from ‘Data.List’ at src/Extension/Prelude.hs:5:1-16
                             (and originally defined in ‘base-4.8.0.0:Data.OldList’)

src/Extension/Prelude.hs:61:29:
    Ambiguous occurrence ‘sortOn’
    It could refer to either ‘Extension.Prelude.sortOn’,
                             defined at src/Extension/Prelude.hs:56:1
                          or ‘Data.List.sortOn’,
                             imported from ‘Data.List’ at src/Extension/Prelude.hs:5:1-16
                             (and originally defined in ‘base-4.8.0.0:Data.OldList’)

src/Extension/Prelude.hs:65:35:
    Ambiguous occurrence ‘sortOn’
    It could refer to either ‘Extension.Prelude.sortOn’,
                             defined at src/Extension/Prelude.hs:56:1
                          or ‘Data.List.sortOn’,
                             imported from ‘Data.List’ at src/Extension/Prelude.hs:5:1-16
                             (and originally defined in ‘base-4.8.0.0:Data.OldList’)
cabal: Error: some packages failed to install:
scyther-proof-0.10.0.0 failed during the building phase. The exception was:
ExitFailure

**Comment by meiersi** [comment]
Ok. I'll work on it. I have to see when my next free evening is. Probably
Thursday.

callalilychen <notifications@github.com> schrieb am Mo., 15. Juni 2015
11:42 PM:

**Comment by meiersi** [comment]
I've pushed a fix and deployed https://hackage.haskell.org/package/scyther-proof-0.10.0.1. Try

```
cabal update
cabal install scyther-proof-0.10.0.1
```

Please reopen if his does not work. Thanks for your patience and happy proving :-)

**Comment by callalilychen** [comment]
It works. Thank you very much!

**Comment by meiersi** [comment]
Great! I'll have more time to fix tamarin-prover next week. Thanks for your
patience.

callalilychen notifications@github.com schrieb am So., 21. Juni 2015 8:52
PM:
